## Simple Linear Regression 

In [1]:
import os 
import pandas as pd

In [2]:
path = r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/Salary_dataset.csv"
df=pd.read_csv(path)
df.head

<bound method NDFrame.head of     Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22  

<!-- mutlivariate normality: error distribution- normally distributed

If the assumptions fails, you must choose another algorithm to build the model

Central tendency

how do you handle missing data

Categorical data

Continuous data

Sourabh Karajage
10:09 AM
SK
mode

mean and median -->

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Unnamed: 0       30 non-null     int64  
 1   YearsExperience  30 non-null     float64
 2   Salary           30 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 852.0 bytes


In [ ]:
## Data cleaning  

In [4]:
df.isna().sum()

Unnamed: 0         0
YearsExperience    0
Salary             0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [ ]:
## Separate X and Y Feature 

In [ ]:
# X: Independent feature => YearsExperience 
# Y : Dependent feature => Salary

In [8]:
df["Salary"]

0      39344.0
1      46206.0
2      37732.0
3      43526.0
4      39892.0
5      56643.0
6      60151.0
7      54446.0
8      64446.0
9      57190.0
10     63219.0
11     55795.0
12     56958.0
13     57082.0
14     61112.0
15     67939.0
16     66030.0
17     83089.0
18     81364.0
19     93941.0
20     91739.0
21     98274.0
22    101303.0
23    113813.0
24    109432.0
25    105583.0
26    116970.0
27    112636.0
28    122392.0
29    121873.0
Name: Salary, dtype: float64

In [9]:
df[['Salary']]

Salary
0    39344.0
1    46206.0
2    37732.0
3    43526.0
4    39892.0
5    56643.0
6    60151.0
7    54446.0
8    64446.0
9    57190.0
10   63219.0
11   55795.0
12   56958.0
13   57082.0
14   61112.0
15   67939.0
16   66030.0
17   83089.0
18   81364.0
19   93941.0
20   91739.0
21   98274.0
22  101303.0
23  113813.0
24  109432.0
25  105583.0
26  116970.0
27  112636.0
28  122392.0
29  121873.0

In [11]:
X = df[['YearsExperience']]
Y = df[['Salary']]

In [12]:
X.head()

YearsExperience
0              1.2
1              1.4
2              1.6
3              2.1
4              2.3

In [13]:
Y.head()

Salary
0  39344.0
1  46206.0
2  37732.0
3  43526.0
4  39892.0

In [ ]:
## There are no missing values nor any duplicated rows in this dataset


In [14]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [15]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer

In [16]:
pipe = make_pipeline(SimpleImputer(strategy='median')).set_output(transform='pandas')

In [17]:
pipe

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median'))])

In [18]:
# fit_transform: fit the data and transform the data based on provided conditions
# tranform : will do only the changes
# # fit: will only fit the changes

In [19]:
df.dtypes

Unnamed: 0           int64
YearsExperience    float64
Salary             float64
dtype: object

In [20]:
# X_pre = pipe.fit_transform(X)
# X_pre.head()

## Model Building : Linear Regression
    Equation of Line: y = B0 + B1.X
    B0 => y intercept
    B1 => Slope of the line

    ProfitPredicted = B0 + B1*RND

In [21]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.


In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [24]:
# B0- y intercept
model.intercept_

array([24848.20396652])

In [25]:
# B1- slope of the line
model.coef_

array([[9449.96232146]])

In [27]:

Y.head()

Salary
0  39344.0
1  46206.0
2  37732.0
3  43526.0
4  39892.0

In [28]:

Ypreds = model.predict(X)
Ypreds

array([[ 36188.15875227],
       [ 38078.15121656],
       [ 39968.14368085],
       [ 44693.12484158],
       [ 46583.11730587],
       [ 53198.09093089],
       [ 54143.08716303],
       [ 56033.07962732],
       [ 56033.07962732],
       [ 60758.06078805],
       [ 62648.05325234],
       [ 63593.04948449],
       [ 63593.04948449],
       [ 64538.04571663],
       [ 68318.03064522],
       [ 72098.0155738 ],
       [ 73988.00803809],
       [ 75878.00050238],
       [ 81547.97789525],
       [ 82492.9741274 ],
       [ 90052.94398456],
       [ 92887.932681  ],
       [100447.90253816],
       [103282.8912346 ],
       [108007.87239533],
       [110842.86109176],
       [115567.84225249],
       [116512.83848464],
       [123127.81210966],
       [125017.80457395]])

In [29]:

Ypreds[0:5]

array([[36188.15875227],
       [38078.15121656],
       [39968.14368085],
       [44693.12484158],
       [46583.11730587]])

In [30]:

Ypreds[:5]

array([[36188.15875227],
       [38078.15121656],
       [39968.14368085],
       [44693.12484158],
       [46583.11730587]])

In [31]:

Y.head()

Salary
0  39344.0
1  46206.0
2  37732.0
3  43526.0
4  39892.0

In [ ]:
# Evaluation Metrics
# Mean Squared Error
# Mean Absolute Error
# RMSE
# R2 squared- R2 score

In [32]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [35]:
mse = mean_squared_error(Y,Ypreds)
mae = mean_absolute_error(Y,Ypreds)
rmse = mse**(1/2)
r2 = r2_score(Y,Ypreds)

print(f"MSE: {mse:.2f}")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R2 score: {r2*100:.2f}%")

MSE: 31270951.72
MAE: 4644.20
RMSE: 5592.04
R2 score: 95.70%
