## Simple Linear Regression 

In [ ]:
import os 
import pandas as pd

In [ ]:
path = r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/50_Startups.csv"
df=pd.read_csv(path)
df.head

<bound method NDFrame.head of           RND      ADMIN        MKT       STATE     PROFIT
0   165349.20  136897.80  471784.10    New York  192261.83
1   162597.70  151377.59  443898.53  California  191792.06
2   153441.51  101145.55  407934.54     Florida  191050.39
3   144372.41  118671.85  383199.62    New York  182901.99
4   142107.34   91391.77  366168.42     Florida  166187.94
5   131876.90   99814.71  362861.36    New York  156991.12
6   134615.46  147198.87  127716.82  California  156122.51
7   130298.13  145530.06  323876.68     Florida  155752.60
8   120542.52  148718.95  311613.29    New York  152211.77
9   123334.88  108679.17  304981.62  California  149759.96
10  101913.08  110594.11  229160.95     Florida  146121.95
11  100671.96   91790.61  249744.55  California  144259.40
12   93863.75  127320.38  249839.44     Florida  141585.52
13   91992.39  135495.07  252664.93  California  134307.35
14  119943.24  156547.42  256512.92     Florida  132602.65
15  114523.61  122616.84  

<!-- mutlivariate normality: error distribution- normally distributed

If the assumptions fails, you must choose another algorithm to build the model

Central tendency

how do you handle missing data

Categorical data

Continuous data

Sourabh Karajage
10:09 AM
SK
mode

mean and median -->

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RND     50 non-null     float64
 1   ADMIN   50 non-null     float64
 2   MKT     50 non-null     float64
 3   STATE   50 non-null     object 
 4   PROFIT  50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [ ]:
## Data cleaning  

In [ ]:
df.isna().sum()

RND       0
ADMIN     0
MKT       0
STATE     0
PROFIT    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
## Separate X and Y Feature 

In [ ]:
# X: Independent feature => RND
# Y : Dependent feature => PROFIT

In [ ]:
df["RND"]

0     165349.20
1     162597.70
2     153441.51
3     144372.41
4     142107.34
5     131876.90
6     134615.46
7     130298.13
8     120542.52
9     123334.88
10    101913.08
11    100671.96
12     93863.75
13     91992.39
14    119943.24
15    114523.61
16     78013.11
17     94657.16
18     91749.16
19     86419.70
20     76253.86
21     78389.47
22     73994.56
23     67532.53
24     77044.01
25     64664.71
26     75328.87
27     72107.60
28     66051.52
29     65605.48
30     61994.48
31     61136.38
32     63408.86
33     55493.95
34     46426.07
35     46014.02
36     28663.76
37     44069.95
38     20229.59
39     38558.51
40     28754.33
41     27892.92
42     23640.93
43     15505.73
44     22177.74
45      1000.23
46      1315.46
47         0.00
48       542.05
49         0.00
Name: RND, dtype: float64

In [ ]:
df[['RND']]

RND
0   165349.20
1   162597.70
2   153441.51
3   144372.41
4   142107.34
5   131876.90
6   134615.46
7   130298.13
8   120542.52
9   123334.88
10  101913.08
11  100671.96
12   93863.75
13   91992.39
14  119943.24
15  114523.61
16   78013.11
17   94657.16
18   91749.16
19   86419.70
20   76253.86
21   78389.47
22   73994.56
23   67532.53
24   77044.01
25   64664.71
26   75328.87
27   72107.60
28   66051.52
29   65605.48
30   61994.48
31   61136.38
32   63408.86
33   55493.95
34   46426.07
35   46014.02
36   28663.76
37   44069.95
38   20229.59
39   38558.51
40   28754.33
41   27892.92
42   23640.93
43   15505.73
44   22177.74
45    1000.23
46    1315.46
47       0.00
48     542.05
49       0.00

In [ ]:
X = df[['RND']]
Y = df[['PROFIT']]

In [ ]:
X.head()

RND
0  165349.20
1  162597.70
2  153441.51
3  144372.41
4  142107.34

In [ ]:
Y.head()

PROFIT
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [ ]:
## There are no missing values nor any duplicated rows in this dataset


In [ ]:
pip install scikit-learn

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer

In [ ]:
pipe = make_pipeline(SimpleImputer(strategy='median')).set_output(transform='pandas')

In [ ]:
pipe

In [ ]:
# fit_transform: fit the data and transform the data based on provided conditions
# tranform : will do only the changes
# # fit: will only fit the changes

In [ ]:
df.dtypes

RND       float64
ADMIN     float64
MKT       float64
STATE      object
PROFIT    float64
dtype: object

In [ ]:
# X_pre = pipe.fit_transform(X)
# X_pre.head()

NameError: name 'pipe' is not defined

## Model Building : Linear Regression
    Equation of Line: y = B0 + B1.X
    B0 => y intercept
    B1 => Slope of the line

    ProfitPredicted = B0 + B1*RND

In [ ]:
pip install scikit-learn


  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.7 MB 4.4 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/8.7 MB 3.8 MB/s eta 0:00:02
   -------- ------------------------------- 1.8/8.7 MB 3.5 MB/s eta 0:00:02
   --------- ------------------------------ 2.1/8.7 MB 3.1 MB/s eta 0:00:03
   ---------------------------- ----------- 6.3/8.7 MB 6.4 MB/s eta 0:00:01
   --------------------------------- ------ 7.3/8.7 MB 6.3 MB/s eta 0:00:01
   -------------------------------------- - 8.4/8.7 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 5.4 MB/s  0:00:01
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   - -------------------------------------- 1.0/38.5 MB 4.9 MB/s eta 0:00:08
   -- ------------------------------------- 2.1/38.5 MB 5.3 MB/s eta 0:00:07
   --- --------------------------

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [ ]:
# B0- y intercept
model.intercept_

array([49032.89914125])

In [ ]:
# B1- slope of the line
model.coef_

array([[0.85429137]])

In [ ]:
# ProfitPredicted = 49032.9 + 0.8542*RND

# RND=0 ProfitPredicted = 49032.9

# Rnd=1 It will increase by 0.854 times

In [ ]:

Y.head()

PROFIT
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [ ]:

Ypreds = model.predict(X)
Ypreds

array([[190289.29389289],
       [187938.71118575],
       [180116.65707807],
       [172369.00320589],
       [170433.97345032],
       [161694.19683741],
       [164033.72501421],
       [160345.46724972],
       [152011.33380847],
       [154396.82286103],
       [136096.36397105],
       [135036.08586475],
       [129219.89081021],
       [127621.20411029],
       [151499.37407569],
       [146869.43093301],
       [115678.82583435],
       [129897.69412683],
       [127413.41482014],
       [122860.50313037],
       [114175.91374003],
       [116000.34693472],
       [112245.81324567],
       [106725.35677792],
       [114850.93206678],
       [104275.40289851],
       [113385.70276482],
       [110633.79960036],
       [105460.14271464],
       [105079.09459155],
       [101994.24845109],
       [101261.18102569],
       [103202.54108032],
       [ 96440.90176556],
       [ 88694.29012885],
       [ 88342.27936946],
       [ 73520.10196791],
       [ 86681.47714396],
       [ 663

In [ ]:

Ypreds[0:5]

array([[190289.29389289],
       [187938.71118575],
       [180116.65707807],
       [172369.00320589],
       [170433.97345032]])

In [ ]:

Ypreds[:5]

array([[190289.29389289],
       [187938.71118575],
       [180116.65707807],
       [172369.00320589],
       [170433.97345032]])

In [ ]:

Y.head()

PROFIT
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

In [ ]:
# Evaluation Metrics
# Mean Squared Error
# Mean Absolute Error
# RMSE
# R2 squared- R2 score